import { Fragment, useMemo, useState } from 'react';
import { useDraggableModal } from '../../components/ui/useDraggableModal';
import type { DirectoryPosition } from './ItemsDirectory';

type SleeveItem = { plu: string; name: string; format: string; client: string; supplier: string; contract: string; basket: string; printRun: number; warehouse: number; production: number; debt: number; weeklySupply: number[]; dailyForecast: number };

const getIsoWeek = (date = new Date()) => { const utc = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate())); const day = utc.getUTCDay() || 7; utc.setUTCDate(utc.getUTCDate() + 4 - day); const yearStart = new Date(Date.UTC(utc.getUTCFullYear(), 0, 1)); return Math.ceil((((utc.getTime() - yearStart.getTime()) / 86400000) + 1) / 7); };
const formatNumber = (value: number) => new Intl.NumberFormat('ru-RU').format(Math.round(value));
const days = (stock: number, forecast: number) => forecast > 0 ? Math.round(stock / forecast) : null;
const formatDays = (value: number | null) => value === null ? '—' : `${value} дн.`;
const stockDate = (coverageDays: number | null) => coverageDays === null ? '—' : new Intl.DateTimeFormat('ru-RU').format(new Date(Date.now() + coverageDays * 86400000));
const printRunLabel = (items: SleeveItem[]) => { const runs = [...new Set(items.map((item) => item.printRun).filter(Boolean))]; return runs.length === 0 ? 'Не задан' : runs.length === 1 ? formatNumber(runs[0]) : 'Разные тиражи'; };
const COMMENTS_KEY = 'analiz-rum:sleeve-comments';
const ORDERS_KEY = 'analiz-rum:sleeve-orders';
const loadComments = () => { try { return JSON.parse(localStorage.getItem(COMMENTS_KEY) ?? '{}') as Record<string, string>; } catch { return {}; } };

export function SleeveAnalysis({ directoryPositions }: { directoryPositions: DirectoryPosition[] }) {
  const [selectedSupplier, setSelectedSupplier] = useState('all');
  const [selectedContract, setSelectedContract] = useState('all');
  const [search, setSearch] = useState('');
  const [formatFilter, setFormatFilter] = useState('');
  const [clientFilter, setClientFilter] = useState('');
  const [comments, setComments] = useState<Record<string, string>>(loadComments);
  const [savedComments, setSavedComments] = useState<Record<string, string>>(loadComments);
  const [isOrderOpen, setIsOrderOpen] = useState(false);
  const [orderSupplier, setOrderSupplier] = useState('');
  const [orderContract, setOrderContract] = useState('all');
  const [orderFormat, setOrderFormat] = useState('');
  const [orderClient, setOrderClient] = useState('');
  const [orderSearch, setOrderSearch] = useState('');
  const [orderQuantities, setOrderQuantities] = useState<Record<string, number>>({});
  const [selectedOrderRows, setSelectedOrderRows] = useState<string[]>([]);
  const [orderSupplierOverrides, setOrderSupplierOverrides] = useState<Record<string, string>>({});
  const [alternateSupplier, setAlternateSupplier] = useState('');
  const orderDrag = useDraggableModal(isOrderOpen);

  const sleeveItems = useMemo(() => directoryPositions.filter((row) => row.category.trim().toLocaleLowerCase('ru') === 'обечайки').map((row): SleeveItem => ({ plu: row.plu, name: row.name, format: row.sleeveFormat || 'Формат не указан', client: row.sleeveClient || 'Клиент не указан', supplier: row.supplier || 'Поставщик не указан', contract: row.contractNumber || '—', basket: row.basketNumber || '—', printRun: row.sleevePrintRun ?? 0, warehouse: 0, production: 0, debt: 0, weeklySupply: [0, 0, 0, 0], dailyForecast: 0 })), [directoryPositions]);
  const suppliers = useMemo(() => [...new Set(sleeveItems.map((item) => item.supplier))].sort((a, b) => a.localeCompare(b, 'ru')).map((name) => { const items = sleeveItems.filter((item) => item.supplier === name); return { name, contract: items.find((item) => item.contract !== '—')?.contract ?? '—', basket: items.find((item) => item.basket !== '—')?.basket ?? '—', formats: [...new Set(items.map((item) => item.format))], positions: items.length }; }), [sleeveItems]);
  const supplierContracts = [...new Set((selectedSupplier === 'all' ? sleeveItems : sleeveItems.filter((item) => item.supplier === selectedSupplier)).map((item) => item.contract).filter(Boolean))];
  const supplierScopedItems = sleeveItems.filter((item) => (selectedSupplier === 'all' || item.supplier === selectedSupplier) && (selectedContract === 'all' || item.contract === selectedContract));
  const formats = [...new Set(supplierScopedItems.map((item) => item.format))];
  const clients = [...new Set(supplierScopedItems.map((item) => item.client))];
  const week = getIsoWeek();
  const weeks = [0, 1, 2, 3].map((offset) => ((week - 1 + offset) % 52) + 1);
  const filtered = useMemo(() => { const query = search.trim().toLocaleLowerCase('ru'); return supplierScopedItems.filter((item) => (!formatFilter || item.format === formatFilter) && (!clientFilter || item.client === clientFilter) && (!query || [item.plu, item.name, item.client, item.supplier, item.contract].some((value) => value.toLocaleLowerCase('ru').includes(query)))); }, [clientFilter, formatFilter, search, supplierScopedItems]);
  const displaySupplierGroups = useMemo(() => [...new Set(filtered.map((item) => item.supplier))].map((supplier) => { const supplierItems = filtered.filter((item) => item.supplier === supplier); return { supplier, contract: supplierItems.find((item) => item.contract !== '—')?.contract ?? '—', basket: supplierItems.find((item) => item.basket !== '—')?.basket ?? '—', items: supplierItems, formats: [...new Set(supplierItems.map((item) => item.format))].map((format) => ({ format, items: supplierItems.filter((item) => item.format === format) })) }; }).filter((group) => group.items.length), [filtered]);

  const orderRowKey = (item: SleeveItem) => `${item.supplier}::${item.contract}::${item.plu}`;
  const effectiveOrderSupplier = (item: SleeveItem) => orderSupplierOverrides[orderRowKey(item)] || item.supplier;
  const effectiveOrderContract = (item: SleeveItem) => {
    const assignedSupplier = orderSupplierOverrides[orderRowKey(item)];
    return assignedSupplier ? suppliers.find((supplier) => supplier.name === assignedSupplier)?.contract ?? item.contract : item.contract;
  };
  const orderSupplierItems = sleeveItems.filter((item) => (orderSupplier === 'all' || effectiveOrderSupplier(item) === orderSupplier) && (orderContract === 'all' || effectiveOrderContract(item) === orderContract));
  const orderContracts = [...new Set(sleeveItems.filter((item) => orderSupplier === 'all' || effectiveOrderSupplier(item) === orderSupplier).map(effectiveOrderContract).filter(Boolean))];
  const orderFormats = [...new Set(orderSupplierItems.map((item) => item.format))];
  const orderClients = [...new Set(orderSupplierItems.map((item) => item.client))];
  const orderPlu = orderSearch.split(/[\s,;]+/).map((value) => value.trim().toLocaleLowerCase('ru')).filter(Boolean);
  const orderItems = orderSupplierItems.filter((item) => (!orderFormat || item.format === orderFormat) && (!orderClient || item.client === orderClient) && (!orderPlu.length || orderPlu.some((query) => item.plu.toLocaleLowerCase('ru').includes(query))));

  const selectSupplier = (supplier: string) => { setSelectedSupplier(supplier); setSelectedContract('all'); setFormatFilter(''); setClientFilter(''); };
  const openOrder = () => { if (!suppliers.length) return; setOrderSupplier(selectedSupplier); setOrderContract(selectedContract); setAlternateSupplier(suppliers[0]?.name ?? ''); setOrderFormat(''); setOrderClient(''); setOrderSearch(''); setSelectedOrderRows([]); setOrderSupplierOverrides({}); setIsOrderOpen(true); };
  const persistComment = (plu: string) => { const next = { ...savedComments, [plu]: comments[plu] ?? '' }; setSavedComments(next); localStorage.setItem(COMMENTS_KEY, JSON.stringify(next)); };
  const deleteComment = (plu: string) => { const next = { ...comments, [plu]: '' }; setComments(next); setSavedComments(next); localStorage.setItem(COMMENTS_KEY, JSON.stringify(next)); };
  const saveOrder = () => {
    const positions = orderItems.flatMap((item) => { const key = orderRowKey(item); const quantity = orderQuantities[key] ?? 0; if (quantity <= 0) return []; const total = item.warehouse + item.production; const transit = item.debt + item.weeklySupply.reduce((sum, value) => sum + value, 0); const coverageDays = days(total + transit + quantity, item.dailyForecast); const supplier = orderSupplierOverrides[key] || item.supplier; const contract = suppliers.find((profile) => profile.name === supplier)?.contract ?? item.contract; return [{ plu: item.plu, name: item.name, format: item.format, client: item.client, supplier, contract, quantity, coverageDays, stockUntil: stockDate(coverageDays) }]; });
    if (!positions.length) return;
    let current: unknown[] = []; try { current = JSON.parse(localStorage.getItem(ORDERS_KEY) ?? '[]') as unknown[]; } catch { current = []; }
    const groupedOrders = [...new Set(positions.map((position) => `${position.supplier}::${position.contract}`))].map((groupKey, index) => { const [supplier, contract] = groupKey.split('::'); return { id: `sleeves-${Date.now()}-${index}`, createdAt: new Date().toISOString(), supplier, contract, positions: positions.filter((position) => position.supplier === supplier && position.contract === contract) }; });
    localStorage.setItem(ORDERS_KEY, JSON.stringify([...current, ...groupedOrders])); setOrderQuantities({}); setIsOrderOpen(false);
  };

  return <section className="sleeve-analysis">
    <div className="sleeve-summary"><article><span>Поставщиков</span><strong>{new Set(filtered.map((item) => item.supplier)).size}</strong></article><article><span>Позиций</span><strong>{filtered.length}</strong></article><article><span>Форматов</span><strong>{new Set(filtered.map((item) => item.format)).size}</strong></article><article className="is-debt"><span>Позиций с долгом</span><strong>{filtered.filter((item) => item.debt > 0).length}</strong></article></div>

    {suppliers.length ? <div className="sleeve-suppliers-panel"><label><span>Поставщик обечаек</span><select value={selectedSupplier} onChange={(event) => selectSupplier(event.target.value)}><option value="all">Все поставщики</option>{suppliers.map((supplier) => <option key={supplier.name} value={supplier.name}>{supplier.name}</option>)}</select></label><label><span>Номер договора</span><select value={selectedContract} onChange={(event) => { setSelectedContract(event.target.value); setFormatFilter(''); setClientFilter(''); }}><option value="all">Все договоры</option>{supplierContracts.map((contract) => <option key={contract}>{contract}</option>)}</select></label><div><span>Форматы</span><strong>{new Set(supplierScopedItems.map((item) => item.format)).size}</strong></div><div><span>Позиции</span><strong>{supplierScopedItems.length}</strong></div></div> : null}

    <div className="sleeve-toolbar"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Найти PLU, наименование, клиента или поставщика" /><select value={formatFilter} onChange={(event) => setFormatFilter(event.target.value)}><option value="">Все форматы</option>{formats.map((format) => <option key={format}>{format}</option>)}</select><select value={clientFilter} onChange={(event) => setClientFilter(event.target.value)}><option value="">Все клиенты</option>{clients.map((client) => <option key={client}>{client}</option>)}</select><button type="button" onClick={() => { setSearch(''); setFormatFilter(''); setClientFilter(''); }}>Очистить</button><button className="dashboard-button dashboard-button--primary" type="button" disabled={!suppliers.length} onClick={openOrder}>Сформировать заказ</button></div>

    <section className="sleeve-section"><header><div><span>Группа</span><h2>Обечайки · ФК · Долгопрудный</h2></div><strong>{filtered.length} позиций</strong></header>
      {displaySupplierGroups.length ? <div className="sleeve-table-wrap"><table className="sleeve-table"><thead><tr><th>PLU</th><th>Наименование позиции</th><th>Клиент</th><th>Комментарий</th><th>Склад</th><th>Производство</th><th>Общий запас</th><th>Долг</th>{weeks.map((number) => <th key={number}>Нед. {number}</th>)}<th>Прогноз / день</th><th>ТЗ</th><th>ТЗ с транзитом</th><th>Дата с транзитом</th></tr></thead><tbody>{displaySupplierGroups.map((supplierGroup) => <Fragment key={supplierGroup.supplier}><tr className="sleeve-supplier-row"><td colSpan={16}><div><span>Поставщик</span><strong>{supplierGroup.supplier}</strong></div><div><span>Договор</span><strong>{supplierGroup.contract}</strong></div><div><span>Номер корзины</span><strong>{supplierGroup.basket}</strong></div><div><span>Позиции</span><strong>{supplierGroup.items.length}</strong></div></td></tr>{supplierGroup.formats.map((group) => <Fragment key={`${supplierGroup.supplier}-${group.format}`}><tr className="sleeve-format-row"><td colSpan={16}><div><span>Формат</span><strong>{group.format}</strong></div><div><span>Тираж заказа</span><strong>{printRunLabel(group.items)}</strong></div><div><span>Позиции</span><strong>{group.items.length}</strong></div></td></tr>{group.items.map((item) => { const total = item.warehouse + item.production; const transit = item.debt + item.weeklySupply.reduce((sum, value) => sum + value, 0); const transitDays = days(total + transit, item.dailyForecast); return <tr key={`${item.supplier}-${item.contract}-${item.plu}`}><td><strong>{item.plu}</strong></td><td>{item.name}</td><td><span className="sleeve-client">{item.client}</span></td><td><div className="sleeve-comment"><textarea value={comments[item.plu] ?? ''} onChange={(event) => setComments({ ...comments, [item.plu]: event.target.value })} placeholder="Добавить комментарий" /><div><button type="button" disabled={(comments[item.plu] ?? '') === (savedComments[item.plu] ?? '')} onClick={() => persistComment(item.plu)}>Сохранить</button><button type="button" onClick={() => deleteComment(item.plu)}>Удалить</button></div></div></td><td className="is-number">{formatNumber(item.warehouse)}</td><td className="is-number">{formatNumber(item.production)}</td><td className="is-number"><strong>{formatNumber(total)}</strong></td><td className={`is-number ${item.debt ? 'is-debt' : ''}`}>{item.debt ? formatNumber(item.debt) : '—'}</td>{item.weeklySupply.map((value, index) => <td className="is-number" key={weeks[index]}>{value ? formatNumber(value) : '—'}</td>)}<td className="is-number">{item.dailyForecast ? formatNumber(item.dailyForecast) : '—'}</td><td className="is-number"><strong>{formatDays(days(total, item.dailyForecast))}</strong></td><td className="is-number"><strong>{formatDays(transitDays)}</strong></td><td className="is-number"><strong>{stockDate(transitDays)}</strong></td></tr>; })}</Fragment>)}</Fragment>)}</tbody></table></div> : <div className="sleeve-empty">В справочнике нет обечаек по выбранным условиям</div>}
    </section>

    {isOrderOpen && <><button className="dashboard-details-backdrop" type="button" aria-label="Закрыть заказ обечаек" onClick={() => setIsOrderOpen(false)} /><aside className="sleeve-order draggable-modal" style={orderDrag.dragStyle} aria-label="Заказ обечаек"><header className="sleeve-order__header draggable-modal__handle" {...orderDrag.dragHandleProps}><div><span>Планирование заказа по поставщикам</span><h2>Общий заказ обечаек</h2></div><button type="button" onClick={() => setIsOrderOpen(false)}>×</button></header>
      <div className="sleeve-order__filters sleeve-order__filters--supplier"><label><span>Поставщик по справочнику</span><select value={orderSupplier} onChange={(event) => { setOrderSupplier(event.target.value); setOrderContract('all'); setOrderFormat(''); setOrderClient(''); setOrderQuantities({}); setSelectedOrderRows([]); }}><option value="all">Все поставщики</option>{suppliers.map((supplier) => <option key={supplier.name}>{supplier.name}</option>)}</select></label><label><span>Договор</span><select value={orderContract} onChange={(event) => setOrderContract(event.target.value)}><option value="all">Все договоры</option>{orderContracts.map((contract) => <option key={contract}>{contract}</option>)}</select></label><label><span>Формат</span><select value={orderFormat} onChange={(event) => setOrderFormat(event.target.value)}><option value="">Все форматы</option>{orderFormats.map((format) => <option key={format}>{format}</option>)}</select></label><label><span>Клиент</span><select value={orderClient} onChange={(event) => setOrderClient(event.target.value)}><option value="">Все клиенты</option>{orderClients.map((client) => <option key={client}>{client}</option>)}</select></label><label><span>PLU — можно вставить несколько кодов</span><textarea rows={2} value={orderSearch} onChange={(event) => setOrderSearch(event.target.value)} placeholder="Вставьте один или несколько PLU" /></label></div>
      <div className="sleeve-order__assignment"><span>Выбрано: <strong>{selectedOrderRows.length}</strong></span><select value={alternateSupplier} onChange={(event) => setAlternateSupplier(event.target.value)}><option value="">Поставщик из справочника</option>{suppliers.map((supplier) => <option key={supplier.name}>{supplier.name}</option>)}</select><button type="button" disabled={!selectedOrderRows.length} onClick={() => setOrderSupplierOverrides((current) => { const next = { ...current }; selectedOrderRows.forEach((key) => { if (alternateSupplier) next[key] = alternateSupplier; else delete next[key]; }); return next; })}>Назначить для заказа</button><small>Меняется только поставщик текущего заказа. Справочник позиций не изменяется.</small></div>
      <div className="sleeve-order__table"><table><thead><tr><th><input type="checkbox" checked={orderItems.length > 0 && orderItems.every((item) => selectedOrderRows.includes(orderRowKey(item)))} onChange={(event) => setSelectedOrderRows(event.target.checked ? orderItems.map(orderRowKey) : [])} aria-label="Выбрать все позиции заказа" /></th><th>PLU / наименование</th><th>Формат</th><th>Клиент</th><th>Поставщик справочника</th><th>Поставщик заказа</th><th>Поставки по неделям</th><th>Текущий ТЗ</th><th>ТЗ с транзитом</th><th>Заказать</th><th>ТЗ с заказом</th><th>Дата с заказом</th></tr></thead><tbody>{orderItems.map((item) => { const key = orderRowKey(item); const total = item.warehouse + item.production; const transit = item.debt + item.weeklySupply.reduce((sum, value) => sum + value, 0); const quantity = orderQuantities[key] ?? 0; const futureDays = days(total + transit + quantity, item.dailyForecast); return <tr key={key}><td><input type="checkbox" checked={selectedOrderRows.includes(key)} onChange={(event) => setSelectedOrderRows((current) => event.target.checked ? [...current, key] : current.filter((value) => value !== key))} aria-label={`Выбрать ${item.plu} для заказа`} /></td><td><strong>{item.plu}</strong><span>{item.name}</span></td><td>{item.format}</td><td>{item.client}</td><td>{item.supplier}<span>{item.contract}</span></td><td><strong>{orderSupplierOverrides[key] || item.supplier}</strong></td><td>{item.weeklySupply.map((value, index) => value ? `${weeks[index]}: ${formatNumber(value)}` : null).filter(Boolean).join(' · ') || 'Нет поставок'}</td><td>{formatDays(days(total, item.dailyForecast))}</td><td>{formatDays(days(total + transit, item.dailyForecast))}</td><td><input type="number" min="0" step="1000" value={quantity || ''} onChange={(event) => setOrderQuantities({ ...orderQuantities, [key]: Number(event.target.value) || 0 })} placeholder="0" /></td><td><strong>{formatDays(futureDays)}</strong></td><td><strong>{stockDate(futureDays)}</strong></td></tr>; })}</tbody></table></div>
      <footer><span>Общий объём заказа: <strong>{formatNumber(Object.values(orderQuantities).reduce((sum, value) => sum + value, 0))}</strong></span><div><button type="button" onClick={() => setIsOrderOpen(false)}>Отменить</button><button className="dashboard-button dashboard-button--primary" type="button" disabled={!Object.values(orderQuantities).some((value) => value > 0)} onClick={saveOrder}>Сохранить заказ</button></div></footer></aside></>}
  </section>;
}
